version: "3.9"
services:
  db:
    container_name: db-Certamen_2_William_Gutierrez
    image: mysql:8.0
    ports:
      - "3307:3307"
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Certamen_2_William_Gutierrez_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel1234
    networks:
      - net-Certamen_2_William_Gutierrez
  web:
    container_name: Certamen_2_William_Gutierrez-web
    depends_on:
      - db
    ports:
      - "8082:80"
    volumes:
      - "./web:/var/www/html"
      - "./httpd.conf:/etc/httpd/conf/httpd.conf"
    image: laravel-php8
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net-Certamen_2_William_Gutierrez
networks:
  net-Certamen_2_William_Gutierrez:
    
